const elfPrefixes = [
  { prefix: 'Ael', meaning: 'knight'},
  { prefix: 'Aer', meaning: 'law'},
  { prefix: 'Af' , meaning: 'ring'},
  { prefix:'Ah' , meaning: 'crafty'},
  { prefix:'Al' , meaning:'sea'},
  { prefix:'Am' , meaning:'swan'},
  { prefix:'Ama' , meaning:'beauty'},
  { prefix:'An' , meaning:'hand'},
  { prefix:'Ang' , meaning: 'glitter'},
  { prefix:'Ansr' , meaning:'rune'},
  { prefix:'Ar' , meaning:'gold'}, 
  { prefix:'Arì' , meaning:'silver'},
  { prefix:'Arn' , meaning:'south'},
  { prefix:'Aza' , meaning:'life'},
  { prefix:'Bael' , meaning: 'guardian'},
  { prefix:'Bes' , meaning:'oath'},
  { prefix:'Cael' , meaning:'archer'},
  { prefix:'Cal' , meaning:'faith'},
  { prefix:'Cas' , meaning:'herald'},
  { prefix:'Cla' , meaning:'rose'},
  { prefix:'Cor' , meaning:'legend'},
  { prefix:'Cy' , meaning:'onyx'},
  { prefix:'Dae' , meaning: 'white'},
  { prefix:'Dho' , meaning:'falcon'},
  { prefix:'Dre' , meaning:'hound'},
  { prefix:'Du' , meaning:'crescent'},
  { prefix:'Eil' , meaning:'azure'}, 
  { prefix:'Eir' , meaning: 'sharp'},
  { prefix:'El' , meaning:'green'},
  { prefix:'Er' , meaning:'boar'},
  { prefix:'Ev' , meaning:'stag'},
  { prefix:'Fera' , meaning:'champion'},
  { prefix:'Fi' , meaning:'rain'},
  { prefix:'Fir' , meaning:'dark'},
  { prefix:'Fis' , meaning:'light'},
  { prefix:'Gael' , meaning: 'pegasus'},
  { prefix:'Gar' , meaning:'owl'},
  { prefix:'Gil' , meaning:'griffin'},
  { prefix:'Ha' , meaning:'free'}, 
  { prefix:'Hu' , meaning:'horse'},
  { prefix:'Ia' , meaning:'day'},
  { prefix:'Il' , meaning:'mist'},
  { prefix:'Ja' , meaning:'staff'},
  { prefix:'Jar' , meaning: 'dove'},
  { prefix:'Ka' , meaning:'dragon'},
  { prefix:'Kan' , meaning:'eagle'},
  { prefix:'Ker' , meaning:'spell'},
  { prefix:'Keth' , meaning: 'wind'},
  { prefix:'Koeh' , meaning:'earth'},
  { prefix:'Kor' , meaning: 'black'},
  { prefix: 'Ky', meaning: 'ruby' },
  { prefix: 'La', meaning: 'night' },
  { prefix: 'Laf', meaning: 'moon' },
  { prefix: 'Lam', meaning: 'east' },
  { prefix: 'Lue', meaning: 'riddle' },
  { prefix: 'Ly', meaning: 'wolf' },
  { prefix: 'Mai', meaning: 'death' },
  { prefix: 'Mal', meaning: 'war' },
  { prefix: 'Mara', meaning: 'priest' },
  { prefix: 'My', meaning: 'emerald' },
  { prefix: 'Na', meaning: 'ancient' },
  { prefix: 'Nai', meaning: 'oak' },
  { prefix: 'Nim', meaning: 'deep' },
  { prefix: 'Nu', meaning: 'hope' },
  { prefix: 'Ny', meaning: 'diamond' },
  { prefix: 'Py', meaning: 'sapphire' },
  { prefix: 'Raer', meaning: 'unicorn' },
  { prefix: 'Re', meaning: 'bear' },
  { prefix: 'Ren', meaning: 'west' },
  { prefix: 'Rhy', meaning: 'jade' },
  { prefix: 'Ru', meaning: 'dream' },
  { prefix: 'Rua', meaning: 'star' },
  { prefix: 'Rum', meaning: 'meadow' },
  { prefix: 'Rid', meaning: 'spear' },
  { prefix: 'Sae', meaning: 'wood' },
  { prefix: 'Seh', meaning: 'soft' },
  { prefix: 'Sel', meaning: 'high' },
  { prefix: 'Sha', meaning: 'sun' },
  { prefix: 'She', meaning: 'age' },
  { prefix: 'Si', meaning: 'cat' },
  { prefix: 'Sim', meaning: 'north' },
  { prefix: 'Sol', meaning: 'history' },
  { prefix: 'Sum', meaning: 'water' },
  { prefix: 'Syl', meaning: 'faerie' },
  { prefix: 'Ta', meaning: 'fox' },
  { prefix: 'Tahl', meaning: 'blade' },
  { prefix: 'Tha', meaning: 'vigil' },
  { prefix: 'Tho', meaning: 'true' },
  { prefix: 'Ther', meaning: 'sky' },
  { prefix: 'Thro', meaning: 'lore' },
  { prefix: 'Tia', meaning: 'magic' },
  { prefix: 'Tra', meaning: 'tree' },
  { prefix: 'Ty', meaning: 'crystal' },
  { prefix: 'Uth', meaning: 'wizard' },
  { prefix: 'Ver', meaning: 'peace' },
  { prefix: 'Vil', meaning: 'finger' },
  { prefix: 'Von', meaning: 'ice' },
  { prefix: 'Ya', meaning: 'bridge' },
  { prefix: 'Za', meaning: 'royal' },
  { prefix: 'Zy', meaning: 'ivory' }
]

export default elfPrefixes;